### PR TITLE
style: adopt PEP 8's style guidelines

### PR DESCRIPTION
**Pull request by lim-james**
> Leaving this as a draft at the moment, as there are some parts I am a little unsure about. Will like to hear from the team on what are some possible adjustments we can make.

## Description

The code base at the moment does not follow any style guide. Thus in this PR, we adopt both the [PEP 8](https://www.python.org/dev/peps/pep-0008/) and [Django](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/) style guides. Our code base style should now head towards the direction of being _**compact**_. Further explanation of how this is achieved can be found in the upcoming section.

### Removal of comments

I did not remove all the comments, only those that reiterate what the respective line/section does. As an author, use comments to explain why you have made a choice, not what the code does. Your code should always clearly explain what it does, if not, fix it so that it is clearer. Here are some of the comments I removed.
```py
# import your functions/classes here
#Check for if the operation got acknowledged and if a data entry got upserted
```

### Limit line lengths to 79 characters

On top of the need to scroll horizontally, long lines of code can be tedious to read and most of the time can be simplified. Check out [Maximum Line Length](https://www.python.org/dev/peps/pep-0008/#maximum-line-length). Not all lines follow this at the moment, most notably those with long URLs. 

```py
assert client['sample_airbnb']['listingsAndReviews'].find_one() is not None, \
       "Document not found"

update_operation = update_project_info(project_details["old_name"],
                                       "name",
                                       project_details["new_name"])
```

### Compact (query) objects

I think the examples will speak for themselves. I have provided 3 examples to show different scenarios

```py
# Before
collection.update_one(
    {
        'email' : user['email'] 
    },
    {
        '$set' : 
        {
            field_to_change : new_info 
        }
    },
    False)

# After
collection.update_one(
    {'email': user['email']},
    {'$set': {field_to_change: new_info}},
    False)
```

```py
# Before
collection.update_one(
    {
        'email' : user['email']
    },
    {
        '$pull': 
        { 
            'projects' : 
            { 
                'name' : project_name 
            }
        } 
    })

# After
collection.update_one(
    {'email': user['email']},
    {'$pull': {'projects': {'name': project_name}}})
```

```py
# Before
collection.update_one(
    {
        'email' : user['email'],
        'projects.name' : project_name,
    },
    {
        '$set' : 
        {
            project_subfield_to_change : new_info 
        }
    })

# After
collection.update_one(
    {
        'email': user['email'],
        'projects.name': project_name,
    },
    {'$set': {project_subfield_to_change: new_info}})
```

### Remove newlines after function declaration

As part of making our code more compact, we should limit the number of blank lines in our functions and only use them to indicate logical sections. Check out [Blank Lines](https://www.python.org/dev/peps/pep-0008/#blank-lines).

```py
# Before
def connect_to_mongo(connection_string):

    # Connect to a mongo client using the given connection string
    return MongoClient(connection_string)

# After
def connect_to_mongo(connection_string):
    # Connect to a mongo client using the given connection string
    return MongoClient(connection_string)
```

### Remove variables use for function result

The result of the queries were being stored in a variable before returning. However, some them were never used elsewhere in the function, making them pointless. Here is an example of the change, coupled with the above points.

```py
# Before
def insert_new_project(project_name):
    
    insert_result = collection.update_one(
        {
            'email' : user['email']
        },
        {
            '$push' : 
            {
                'projects' : 
                {
                    'name' : project_name 
                } 
            } 
        })

    return insert_result

# After
def insert_new_project(project_name):
    return collection.update_one(
        {'email': user['email']},
        {'$push': {'projects': {'name': project_name}}})
```

### CODE REVIEW

**Comment by ryantanzr** [comment]
Lgtm!

**Review by irwenyap — APPROVED** [review]
Looking good, code looks clean following this guideline despite it being compact :D

**Review by ryantanzr — COMMENTED** [review]
LGTM

**Review by ryantanzr — COMMENTED** [review]
Files reviewed, no issues here

**Pull request merged**
